from typing import Protocol


class CredentialStore(Protocol):
    @property
    def available(self) -> bool: ...

    def get(self, account: str) -> str: ...

    def set(self, account: str, secret: str) -> None: ...

    def delete(self, account: str) -> None: ...